# Generated by Django 3.0.7 on 2020-07-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
